In [2]:
import re
import math
from collections import Counter


def get_cosine(vec1, vec2):
    intersection = set(vec1.keys()) & set(vec2.keys())
    numerator = sum([vec1[x] * vec2[x] for x in intersection])

    sum1 = sum([vec1[x]**2 for x in vec1.keys()])
    sum2 = sum([vec2[x]**2 for x in vec2.keys()])
    denominator = math.sqrt(sum1) * math.sqrt(sum2)

    if not denominator:
        return 0.0
    else:
        return float(numerator) / denominator
    

def text_to_vector(text):
    word = re.compile(r'\w+')
    words = word.findall(text)
    return Counter(words)


def get_result(content_a, content_b):
    text1 = content_a
    text2 = content_b

    vector1 = text_to_vector(text1)
    vector2 = text_to_vector(text2)

    cosine_result = get_cosine(vector1, vector2)
    return cosine_result


print (get_result('I love github', 'Who love github'))

0.6666666666666667


In [3]:
import pandas as pd
import numpy as np
import spacy

In [4]:
people = pd.read_csv('people_wiki.csv')
people = people.set_index('name')
people.head()

URI  \
name                                                                     
Digby Morrell              <http://dbpedia.org/resource/Digby_Morrell>   
Alfred J. Lewy            <http://dbpedia.org/resource/Alfred_J._Lewy>   
Harpdog Brown              <http://dbpedia.org/resource/Harpdog_Brown>   
Franz Rottensteiner  <http://dbpedia.org/resource/Franz_Rottensteiner>   
G-Enka                            <http://dbpedia.org/resource/G-Enka>   

                                                                  text  
name                                                                    
Digby Morrell        digby morrell born 10 october 1979 is a former...  
Alfred J. Lewy       alfred j lewy aka sandy lewy graduated from un...  
Harpdog Brown        harpdog brown is a singer and harmonica player...  
Franz Rottensteiner  franz rottensteiner born in waidmannsfeld lowe...  
G-Enka               henry krvits born 30 december 1974 in tallinn ...

In [5]:
people = people.reset_index()
people['name'] = people['name'].str.replace("%","")
people['name'] = people['name'].str.replace("(","")
people['name'] = people['name'].str.replace(")","")
people = people.sort_values(by='name', ascending=True)

In [6]:
people = people.set_index('name')
people.head()

URI  \
name                                                                 
 Renate Lorenz   <http://dbpedia.org/resource/Pauline_Boudry_/_...   
1.8.7                          <http://dbpedia.org/resource/1.8.7>   
108 artist              <http://dbpedia.org/resource/108_(artist)>   
14th Dalai Lama      <http://dbpedia.org/resource/14th_Dalai_Lama>   
50 Cent                      <http://dbpedia.org/resource/50_Cent>   

                                                              text  
name                                                                
 Renate Lorenz   pauline boudry renate lorenz are an artist duo...  
1.8.7            187 is a pseudonym for jordana lesesne a music...  
108 artist       108 born 1978 is an italian artist in the fiel...  
14th Dalai Lama  the 14th dalai lama religious name tenzin gyat...  
50 Cent          curtis james jackson iii born july 6 1975 bett...

In [8]:
elton = people.loc['Elton John','text']
vic = people.loc['Victoria Beckham']['text']
paul = people.loc['Paul McCartney','text']

## Word - Count as Feature

In [9]:
from collections import Counter

In [10]:
#Create a list of dictionaries of word count
word_counts = []
for name in people.index:
    doc = people.loc[name,'text']
    word_counts.append(dict(Counter(doc.split(' '))))
    

In [11]:
#Create a column for storing the raw word counts
people['word_counts'] = word_counts

In [12]:
people['word_counts']

name
 Renate Lorenz                {'they': 1, 'mathias': 1, 'gallery': 1, 'part'...
1.8.7                         {'known': 3, '187': 2, 'after': 1, 'artist': 1...
108 artist                    {'asalto': 1, 'invade': 1, 'void': 1, 'playing...
14th Dalai Lama               {'physics': 1, 'two': 1, 'known': 2, 'tibetthe...
50 Cent                       {'known': 1, 'hop': 1, 'after': 2, 'artist': 1...
8 Ball Aitken                 {'release': 1, 'australia': 2, 'hits': 1, 'cou...
8th Arjia Rinpoche            {'given': 1, 'culture': 1, 'known': 1, '2005':...
A Skillz                      {'austria': 1, 'known': 1, 'australia': 1, 'pa...
A-Lee                         {'known': 1, 'rdhusplassen': 1, 'was': 2, 'aft...
A. A. Gill                    {'britain': 1, 'review': 1, 'restraints': 1, '...
A. B. Krongard                {'on': 1, 'marine': 1, 'after': 1, 'in': 4, 'f...
A. B. McKillop                {'court': 1, 'was': 2, 'spinster': 2, 'in': 8,...
A. Baha Balantekin            {'phy

In [13]:
#Get Elton John's Word Count
elton_john_word_count = people.loc['Elton John', 'word_counts']

In [25]:
#Get Elton John's Word Count
elton_john_word_count

{'1': 2,
 '10': 1,
 '100': 3,
 '1947': 1,
 '1967': 1,
 '19702000': 1,
 '1976': 1,
 '1980s': 1,
 '1988': 1,
 '1992': 1,
 '1994': 1,
 '1996': 1,
 '1997': 2,
 '1998': 1,
 '2': 1,
 '200': 1,
 '2002': 1,
 '2004': 2,
 '2005': 1,
 '2008': 1,
 '2012he': 1,
 '2013': 1,
 '2014': 1,
 '21': 2,
 '25': 1,
 '27': 1,
 '30': 1,
 '300': 1,
 '31': 1,
 '33': 1,
 '40': 2,
 '49': 1,
 '58': 1,
 'a': 10,
 'abbey': 1,
 'about': 1,
 'academy': 3,
 'actor': 1,
 'after': 1,
 'against': 1,
 'aids': 2,
 'albums': 2,
 'all': 1,
 'alltime': 1,
 'an': 3,
 'and': 15,
 'announced': 1,
 'annual': 1,
 'artist': 1,
 'artists': 2,
 'as': 2,
 'at': 4,
 'authors': 1,
 'award': 5,
 'awards': 3,
 'be': 1,
 'became': 1,
 'become': 1,
 'been': 3,
 'began': 1,
 'bernie': 1,
 'bestselling': 2,
 'billboard': 4,
 'bisexual': 1,
 'born': 1,
 'brit': 1,
 'british': 3,
 'brits': 1,
 'buckingham': 1,
 'career': 1,
 'cbe': 1,
 'center': 1,
 'champion': 1,
 'charitable': 1,
 'civil': 1,
 'collaborated': 1,
 'commander': 1,
 'composer': 1,


In [30]:
m = -100

ele = ''
for item in elton_john_word_count.keys():
    if(elton_john_word_count[item] >= m):
        m = elton_john_word_count[item]
        ele = item
ele

'the'

In [15]:
#Get Victoria's Word Count
vic_word_count = people.loc['Victoria Beckham', 'word_counts']

### Sort The Word Counts

In [16]:
help(vic_word_count.items)

Help on built-in function items:

items(...) method of builtins.dict instance
    D.items() -> a set-like object providing a view on D's items



In [19]:
d = {'A':1,'B':2,'C':3}
for k,v in d.items():
    print("{} --> {}" .format(k,v))

B --> 2
A --> 1
C --> 3


In [20]:
vic_keys = []
vic_values = []
for (k,v) in vic_word_count.items():
    vic_keys.append(k)
    vic_values.append(v)
        
    

In [21]:
elton_keys = []
elton_values = []
for (k,v) in elton_john_word_count.items():
    elton_keys.append(k)
    elton_values.append(v)
        

### Stack Vectors 

In [33]:
Elton_word_count_table = pd.DataFrame({'Words':elton_keys,'Counts':elton_values},columns=['Words','Counts'])

In [34]:
Elton_word_count_table.head()

Words  Counts
0   palace       2
1  culture       1
2     they       1
3    legal       1
4       58       1

In [35]:
Elton_word_count_table.sort_values(by='Counts', ascending=False)

Words  Counts
124            the      27
14              in      18
153            and      15
101             of      13
166              a      10
95             has       9
102           john       7
196             he       7
208             on       6
115          since       5
104            for       5
203          award       5
184             to       4
116             is       4
240             at       4
93             top       4
205            his       4
226      billboard       4
41            than       3
35           elton       3
191           more       3
50            into       3
33             him       3
67         million       3
99              an       3
214             no       3
24         academy       3
147        british       3
150          music       3
238            one       3
..             ...     ...
138     knighthood       1
140           such       1
108       bisexual       1
107            all       1
106        kennedy       1
103   contribution       1
72          making       1
73              be       1
74         outside       1
75             300       1
76           named       1
78     partnership       1
79            2013       1
80        princess       1
81        inducted       1
82   tonightcandle       1
83      occasional       1
85      successful       1
86           march       1
87            song       1
88           least       1
90             two       1
91          datein       1
92         kenneth       1
94            tony       1
96           later       1
97         authors       1
98         diamond       1
100           four       1
254           2002       1

[255 rows x 2 columns]

In [31]:
Victoria_word_count_table = pd.DataFrame({'Words':vic_keys,'Counts':vic_values},columns=['Words','Counts'])

In [22]:
Victoria_word_count_table.sort_values(by='Counts', ascending=False)

Words  Counts
142        the      19
136         in      12
135        and      12
106    beckham       8
144         of       6
66          to       6
44           a       5
5          she       5
53     fashion       5
50    designer       4
151   victoria       4
68         was       4
39          an       4
173        has       4
153      spice       3
40       label       3
33          uk       3
7          had       3
94         her       3
20        2011       3
148         is       3
45        been       2
35   following       2
71        with       2
43          as       2
128      girls       2
57     records       2
81       brand       2
139       four       2
17         top       2
..         ...     ...
85     belinda       1
86      become       1
1        other       1
88     english       1
89     clamour       1
90        from       1
91    official       1
92        made       1
93   estimated       1
95        ugly       1
78        2008       1
76       split       1
54       april       1
75        icon       1
55   performer       1
56          on       1
58         now       1
59       cameo       1
60       issue       1
61       guest       1
62        born       1
63       about       1
64       being       1
65   millionin       1
69        2014       1
70        york       1
72         out       1
73         who       1
74    biannual       1
174    america       1

[175 rows x 2 columns]

In [23]:
people.columns

Index(['URI', 'text', 'word_counts'], dtype='object')

## TF-IDF as Feature

In [25]:
#Using TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

tf_idf_vectorizer = TfidfVectorizer(analyzer='word')

#tf_idf_matrix = tf_idf_vectorizer.fit_transform([elton,vic,paul])

#tf_idf_matrix

In [ ]:
tf_idf_elton = tf_idf_vectorizer.fit_transform([elton])
tf_idf_vic = tf_idf_vectorizer.fit_transform([vic])


In [26]:
#Get the entire corpus
corpus = []
for name in people.index:
    person = people.loc[name,'text']
    corpus.append(person)    

In [27]:
people = people.reset_index()

### TF-IDF Of Entire Corpus

In [24]:
tf_idf_matrix = tf_idf_vectorizer.fit_transform(corpus)

NameError: name 'tf_idf_vectorizer' is not defined

### TF-IDF of Elton John

In [51]:
tf_idf_elton = tf_idf_vectorizer.fit_transform([elton])

In [52]:
tf_idf_elton.data

array([0.02088324, 0.06264973, 0.02088324, 0.14618271, 0.02088324,
       0.02088324, 0.02088324, 0.02088324, 0.02088324, 0.02088324,
       0.02088324, 0.02088324, 0.08353298, 0.06264973, 0.02088324,
       0.02088324, 0.04176649, 0.02088324, 0.02088324, 0.02088324,
       0.02088324, 0.31324867, 0.02088324, 0.02088324, 0.14618271,
       0.1879492 , 0.02088324, 0.04176649, 0.02088324, 0.02088324,
       0.02088324, 0.04176649, 0.08353298, 0.02088324, 0.10441622,
       0.02088324, 0.02088324, 0.02088324, 0.02088324, 0.12529947,
       0.06264973, 0.06264973, 0.02088324, 0.04176649, 0.08353298,
       0.02088324, 0.02088324, 0.02088324, 0.04176649, 0.02088324,
       0.06264973, 0.02088324, 0.02088324, 0.06264973, 0.06264973,
       0.27148218, 0.5638476 , 0.04176649, 0.06264973, 0.04176649,
       0.3758984 , 0.02088324, 0.02088324, 0.08353298, 0.04176649,
       0.02088324, 0.02088324, 0.02088324, 0.04176649, 0.06264973,
       0.02088324, 0.02088324, 0.08353298, 0.02088324, 0.02088

In [56]:
tf_idf_elton_np = np.array(tf_idf_elton.data)

In [54]:
type(tf_idf_elton)

scipy.sparse.csr.csr_matrix

In [59]:
tf_idf_elton_np = np.resize(tf_idf_elton_np, (1,252))

In [60]:
tf_idf_elton_np.shape

(1, 252)

In [61]:
tf_idf_elton_np

array([[0.02088324, 0.06264973, 0.02088324, 0.14618271, 0.02088324,
        0.02088324, 0.02088324, 0.02088324, 0.02088324, 0.02088324,
        0.02088324, 0.02088324, 0.08353298, 0.06264973, 0.02088324,
        0.02088324, 0.04176649, 0.02088324, 0.02088324, 0.02088324,
        0.02088324, 0.31324867, 0.02088324, 0.02088324, 0.14618271,
        0.1879492 , 0.02088324, 0.04176649, 0.02088324, 0.02088324,
        0.02088324, 0.04176649, 0.08353298, 0.02088324, 0.10441622,
        0.02088324, 0.02088324, 0.02088324, 0.02088324, 0.12529947,
        0.06264973, 0.06264973, 0.02088324, 0.04176649, 0.08353298,
        0.02088324, 0.02088324, 0.02088324, 0.04176649, 0.02088324,
        0.06264973, 0.02088324, 0.02088324, 0.06264973, 0.06264973,
        0.27148218, 0.5638476 , 0.04176649, 0.06264973, 0.04176649,
        0.3758984 , 0.02088324, 0.02088324, 0.08353298, 0.04176649,
        0.02088324, 0.02088324, 0.02088324, 0.04176649, 0.06264973,
        0.02088324, 0.02088324, 0.08353298, 0.02

In [65]:
tf_idf_elton_np.sort()

In [67]:
tf_idf_elton_np

array([[0.02088324, 0.02088324, 0.02088324, 0.02088324, 0.02088324,
        0.02088324, 0.02088324, 0.02088324, 0.02088324, 0.02088324,
        0.02088324, 0.02088324, 0.02088324, 0.02088324, 0.02088324,
        0.02088324, 0.02088324, 0.02088324, 0.02088324, 0.02088324,
        0.02088324, 0.02088324, 0.02088324, 0.02088324, 0.02088324,
        0.02088324, 0.02088324, 0.02088324, 0.02088324, 0.02088324,
        0.02088324, 0.02088324, 0.02088324, 0.02088324, 0.02088324,
        0.02088324, 0.02088324, 0.02088324, 0.02088324, 0.02088324,
        0.02088324, 0.02088324, 0.02088324, 0.02088324, 0.02088324,
        0.02088324, 0.02088324, 0.02088324, 0.02088324, 0.02088324,
        0.02088324, 0.02088324, 0.02088324, 0.02088324, 0.02088324,
        0.02088324, 0.02088324, 0.02088324, 0.02088324, 0.02088324,
        0.02088324, 0.02088324, 0.02088324, 0.02088324, 0.02088324,
        0.02088324, 0.02088324, 0.02088324, 0.02088324, 0.02088324,
        0.02088324, 0.02088324, 0.02088324, 0.02

In [ ]:
#TF-IDF For ELton John

from collections import Counter
import pandas as pd
import math

Statements = corpus
ind = people.index
result_set = set()
row = {}
for stm,i in zip(Statements,ind):
    try:  
        if(i not in row.keys()):
            print(i)
            #print(Counter(temp.loc[i,'text'].split(' ')))
            row[i] = Counter(temp.loc[i,'text'].split(' '))
            print(row[i])
    except:
        print(i)
        continue
    if(not result_set):
        for ele in stm.lower().split(' '):
            result_set.add(ele)
            continue
    result_set = result_set.union(set(stm.lower().strip(',').split(' ')))

column = list(result_set)

#Create an empty data frame
df = pd.DataFrame(index=ind, columns=column)

#Filling the Data Frame 
for col in column:
    for key in row.keys():
        if(col in row[key].keys()):
            df.loc[key][col] = row[key][col]
        else:
            df.loc[key][col] = 0


In [71]:
type(tf_idf_matrix)

scipy.sparse.csr.csr_matrix

In [72]:
tf_idf_matrix.shape

(59071, 548429)

In [73]:
#Reshape the numpy array
tf_idf = tf_idf_matrix.data
tf_idf = np.resize(tf_idf, (59071,38))
tf_idf

array([[0.13968618, 0.10397559, 0.08452409, ..., 0.04278166, 0.03003011,
        0.03835734],
       [0.08595554, 0.06121861, 0.04001736, ..., 0.08312346, 0.01235485,
        0.043529  ],
       [0.06075957, 0.10397559, 0.07619834, ..., 0.04002522, 0.03557476,
        0.14408241],
       ...,
       [0.04378045, 0.0330434 , 0.03538275, ..., 0.06816512, 0.06914643,
        0.05632572],
       [0.05306926, 0.08431014, 0.11171111, ..., 0.01514673, 0.15844412,
        0.16443381],
       [0.30234438, 0.02637546, 0.01294426, ..., 0.03002465, 0.04717444,
        0.04761351]])

In [74]:
#Convert the tf-idf matrix to dataframe
TF_IDF = pd.DataFrame(tf_idf)
TF_IDF

0         1         2         3         4         5         6   \
0      0.139686  0.103976  0.084524  0.084118  0.052941  0.012398  0.032771   
1      0.085956  0.061219  0.040017  0.050898  0.107848  0.046193  0.075214   
2      0.060760  0.103976  0.076198  0.095884  0.062089  0.086865  0.092478   
3      0.207951  0.026642  0.107848  0.030695  0.030315  0.145970  0.080037   
4      0.070394  0.031229  0.020044  0.050489  0.030927  0.030748  0.045864   
5      0.027932  0.095884  0.095884  0.015564  0.036447  0.019268  0.037055   
6      0.033309  0.016423  0.089603  0.034541  0.549651  0.063410  0.044988   
7      0.014823  0.038841  0.015916  0.037782  0.116263  0.040099  0.077032   
8      0.017230  0.033633  0.033591  0.037724  0.032780  0.029933  0.053350   
9      0.057242  0.034775  0.038052  0.052900  0.019129  0.108616  0.028561   
10     0.028280  0.016441  0.036600  0.047181  0.026732  0.088810  0.084848   
11     0.017781  0.036030  0.033308  0.045337  0.079355  0.059518  0.018671   
12     0.033126  0.030276  0.049697  0.036744  0.039094  0.031762  0.033605   
13     0.018317  0.032114  0.165500  0.039772  0.088568  0.176420  0.026665   
14     0.055682  0.058593  0.025550  0.033896  0.080033  0.013982  0.040508   
15     0.038753  0.089472  0.124511  0.070429  0.161895  0.051082  0.048474   
16     0.027430  0.097684  0.100946  0.033939  0.074839  0.057168  0.060213   
17     0.104756  0.088804  0.060360  0.062328  0.120040  0.034077  0.077208   
18     0.023894  0.048950  0.040909  0.041612  0.042310  0.012233  0.020318   
19     0.173576  0.018590  0.057444  0.070497  0.243142  0.124149  0.019935   
20     0.039461  0.030951  0.068048  0.079661  0.073867  0.076234  0.063919   
21     0.030424  0.042269  0.041770  0.051647  0.021644  0.053303  0.021540   
22     0.010731  0.062271  0.011722  0.010213  0.022023  0.029339  0.051298   
23     0.026052  0.027856  0.073947  0.066655  0.035166  0.023893  0.022981   
24     0.067834  0.070374  0.039140  0.046311  0.044633  0.053898  0.038617   
25     0.027050  0.266090  0.069608  0.033812  0.025382  0.033616  0.028566   
26     0.031292  0.026475  0.064228  0.051633  0.038028  0.043020  0.076136   
27     0.023578  0.006847  0.044297  0.026228  0.011464  0.022492  0.016971   
28     0.012607  0.018700  0.060975  0.072399  0.063993  0.016053  0.019483   
29     0.075677  0.094546  0.068605  0.121989  0.024287  0.027265  0.018971   
...         ...       ...       ...       ...       ...       ...       ...   
59041  0.021137  0.047219  0.016161  0.020883  0.018251  0.012119  0.035844   
59042  0.018455  0.016005  0.017604  0.026640  0.030535  0.075956  0.034056   
59043  0.022893  0.052439  0.180701  0.032825  0.032610  0.035439  0.029804   
59044  0.035072  0.040629  0.040762  0.037525  0.028714  0.061038  0.032954   
59045  0.045029  0.117448  0.107446  0.056039  0.049191  0.049965  0.055445   
59046  0.010004  0.032211  0.034831  0.032783  0.018392  0.045401  0.028562   
59047  0.028061  0.054062  0.038547  0.034942  0.032837  0.046408  0.081209   
59048  0.033792  0.079243  0.047826  0.029532  0.041616  0.040893  0.055843   
59049  0.043009  0.048422  0.106306  0.053124  0.043892  0.051887  0.041881   
59050  0.065857  0.141491  0.207277  0.065986  0.064555  0.222171  0.089536   
59051  0.048900  0.016919  0.035400  0.018579  0.016160  0.020054  0.021533   
59052  0.028829  0.081725  0.022168  0.046934  0.021855  0.031783  0.025632   
59053  0.032113  0.037754  0.027901  0.049582  0.030797  0.122420  0.062662   
59054  0.100096  0.050922  0.049112  0.050845  0.045243  0.044904  0.052743   
59055  0.014608  0.029654  0.071449  0.007154  0.071693  0.190409  0.093435   
59056  0.019785  0.031665  0.018444  0.017951  0.018022  0.028877  0.027566   
59057  0.013576  0.031976  0.016254  0.017362  0.110278  0.018496  0.027856   
59058  0.025469  0.032114  0.032753  0.022835  0.159288  0.018648  0.022657   
59059  0.044222  0.037623  0.040257  0.037791  0.028131  0.0289

In [22]:
TF_IDF.index

NameError: name 'TF_IDF' is not defined

In [23]:
TF_IDF.columns

NameError: name 'TF_IDF' is not defined

In [17]:
help(TF_IDF.drop)

Help on method drop in module pandas.core.generic:

drop(labels, axis=0, level=None, inplace=False, errors='raise') method of pandas.core.frame.DataFrame instance
    Return new object with labels in requested axis removed
    
    Parameters
    ----------
    labels : single label or list-like
    axis : int or axis name
    level : int or level name, default None
        For MultiIndex
    inplace : bool, default False
        If True, do operation inplace and return None.
    errors : {'ignore', 'raise'}, default 'raise'
        If 'ignore', suppress error and existing labels are dropped.
    
        .. versionadded:: 0.16.1
    
    Returns
    -------
    dropped : type of caller



In [76]:
TF_IDF.shape

(59071, 38)

In [84]:
people = people.set_index('name')

In [85]:
ind = list(people.index)

In [86]:
len(ind)

59071

In [105]:
if('Elton John') in ind:
    ind.remove('Elton John')
len(ind)    

59070

In [87]:
ind

[' Renate Lorenz',
 '1.8.7',
 '108 artist',
 '14th Dalai Lama',
 '50 Cent',
 '8 Ball Aitken',
 '8th Arjia Rinpoche',
 'A Skillz',
 'A-Lee',
 'A. A. Gill',
 'A. B. Krongard',
 'A. B. McKillop',
 'A. Baha Balantekin',
 'A. Charles Baillie',
 'A. D. Miles',
 'A. Dakshinamurthy',
 'A. David Andrews',
 'A. David Buckingham',
 'A. F. Th. van der Heijden',
 'A. G. Hopkins',
 'A. H. Almaas',
 'A. J. Duhe',
 'A. J. Gass',
 'A. J. Hammer',
 'A. J. Hartley',
 'A. J. Pagano',
 'A. J. Spiker',
 'A. K. Moorthy',
 'A. K. Singh',
 'A. L. Mestel',
 'A. N. Yiannopoulos',
 'A. P. J. Abdul Kalam',
 'A. R. Penck',
 'A. R. Rahman',
 'A. Raja',
 'A. Ramana Rao',
 'A. Roger Merrill',
 'A. Ronald Gallant',
 'A. S. P. Liyanage',
 'A. Scott Loveless',
 'A. Thomas McLellan',
 'A. V. Bellarmin',
 'A. V. Gurava Reddy',
 'A. V. Phibes',
 'A. W. F. Edwards',
 'A. W. Moore philosopher',
 'A.D. Maddox',
 'A.E. Muthunayagam',
 'A.G. Russell',
 'A.J. Styles',
 'A.L.T.',
 'A.V. Balakrishnan',
 'A.W. Hill',
 'AMFJ',
 'AMG 

In [88]:
TF_IDF = TF_IDF.set_index(people.index)

In [89]:
TF_IDF.shape

(59071, 38)

In [112]:
tf_idf_Elton = TF_IDF.loc['Elton John',:]
tf_idf_Vic = TF_IDF.loc['Victoria Beckham',:]

In [91]:
tf_idf_Elton.shape

(38,)

In [92]:
tf_idf_Elton = tf_idf_Elton.reshape(1,38)

In [93]:
#Convert the Elton and Vic vectors to (1,38)
tf_idf_Elton.shape

(1, 38)

In [94]:
tf_idf_Elton

array([[0.08497348, 0.08779559, 0.08497348, 0.08111573, 0.08013005,
        0.1000808 , 0.08222491, 0.18392143, 0.1000808 , 0.08060919,
        0.09196072, 0.07229433, 0.1000808 , 0.1000808 , 0.1000808 ,
        0.1000808 , 0.1000808 , 0.08779559, 0.1000808 , 0.01359991,
        0.06291494, 0.02675401, 0.14676923, 0.01259667, 0.17882722,
        0.10476774, 0.0251345 , 0.03290245, 0.02640021, 0.04306002,
        0.02710589, 0.01180788, 0.03819387, 0.01130711, 0.02247797,
        0.0447505 , 0.01496443, 0.02071519]])

In [95]:
tf_idf_Vic.shape

(38,)

In [96]:
tf_idf_Vic = tf_idf_Vic.reshape(1,38)
tf_idf_Vic.shape

(1, 38)

In [98]:
TF_IDF.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37],
           dtype='int64')

In [101]:
from sklearn.metrics import euclidean_distances as ED

In [118]:
t = TF_IDF.iloc[0,:]
print(t.shape)
t = t.reshape(1,38)
print(t.shape)

(38,)
(1, 38)


In [119]:
t

array([[0.07316924, 0.26606995, 0.07760374, 0.12416598, 0.2638527 ,
        0.24168021, 0.36141168, 0.58757114, 0.05764849, 0.23502846,
        0.09977623, 0.27493895, 0.04434499, 0.24833195, 0.01211908,
        0.19511796, 0.05986574, 0.12638323, 0.03548741, 0.03351194,
        0.06651749, 0.10642798, 0.03711936, 0.03930789, 0.00574096,
        0.04877949, 0.08868998, 0.0035451 , 0.03153302, 0.00859815,
        0.00466033, 0.00556373, 0.02216568, 0.00703639, 0.06321271,
        0.32112056, 0.07838376, 0.16182454]])

In [150]:
tf_idf_Elton = tf_idf_Elton.reshape(1,-1)

In [152]:
def dist(name):
    return (name,ED(TF_IDF.loc[name,:].reshape(1,-1), tf_idf_Elton))

In [104]:
TF_IDF.index[:10]

Index([' Renate Lorenz', '1.8.7', '108 artist', '14th Dalai Lama', '50 Cent',
       '8 Ball Aitken', '8th Arjia Rinpoche', 'A Skillz', 'A-Lee',
       'A. A. Gill'],
      dtype='object', name='name')

In [145]:
TF_IDF.loc['Elton John',:].reshape(1,-1)

array([[0.08497348, 0.08779559, 0.08497348, 0.08111573, 0.08013005,
        0.1000808 , 0.08222491, 0.18392143, 0.1000808 , 0.08060919,
        0.09196072, 0.07229433, 0.1000808 , 0.1000808 , 0.1000808 ,
        0.1000808 , 0.1000808 , 0.08779559, 0.1000808 , 0.01359991,
        0.06291494, 0.02675401, 0.14676923, 0.01259667, 0.17882722,
        0.10476774, 0.0251345 , 0.03290245, 0.02640021, 0.04306002,
        0.02710589, 0.01180788, 0.03819387, 0.01130711, 0.02247797,
        0.0447505 , 0.01496443, 0.02071519]])

In [153]:
tf_idf_Elton.shape

(1, 38)

In [121]:
for ele in map(lambda x: x**2, range(5)):
    print(ele)


0
1
4
9
16


In [134]:
t = [(4,5)]
t[0][1]

5

In [136]:
d_1 = {'a':1}
d_2 = {'b':2,'c':3}
d_1.update(d_2)
d_1

{'a': 1, 'b': 2, 'c': 3}

In [155]:
#f_max = -1000
#s_max = -1000
#Remove Elton from TF_IDF
TF_IDF_without_elton = TF_IDF.drop('Elton John', axis=0)
col = TF_IDF_without_elton.columns
#print((TF_IDF_without_elton.loc[:,col]))
l = []
for name in TF_IDF_without_elton.index:
    l.append(dist(name))
      
def form_dict(low, high,l):
    d = dict()
    mid = (low+high)/2
    if(low>high):
        return
    if(low==high):
        d[l[low][0]] = l[low][1]
        return d
    return form_dict(low,mid,l).update(form_dict(mid+1,high,l))
consolidated_dict = form_dict(0,len(l)-1,l)
'''
f_m = map(lambda name: dist(name, tf_idf_Elton), TF_IDF_without_elton.loc[:,col])
#f_m = max(f_m)

for dis in f_m:
    print(dis)
'''

TypeError: 'NoneType' object is not iterable

In [131]:
temp = TF_IDF
temp = np.array(temp).reshape(59070, 38)

ValueError: cannot reshape array of size 2244698 into shape (59070,38)

In [132]:
TF_IDF.shape

(59070, 38)

In [137]:
#TF_IDF.drop('Elton John',axis=0,inplace=True,errors='raise')
#(df[['lat', 'long']] - np.array(L1)).pow(2).sum(1).pow(0.5)
dis_elton_tf_idf = ((temp - tf_idf_Elton)**(2)).sum(1)**(0.5)


In [ ]:
TF_IDF[]

In [139]:
len(dis_elton_tf_idf)

59070

In [140]:
dis_elton_tf_idf

array([1.15396317, 1.06986275, 1.16754884, ..., 1.42740415, 1.41691044,
       1.34776114])

In [ ]:
#Insert Elton John's value back into the TF_IDF Data frame


In [141]:
np.max(dis_elton_tf_idf)
#Previous Value:- 1.4974619858032765 = New Value
#New Value:- 0.7353526323760786

1.4974619858032767

In [143]:
#Get the index of the maximum element in a numpy array
dis_elton_tf_idf.argmax(axis=0)

34037

In [144]:
TF_IDF = TF_IDF.reset_index()
max_dis_elton = TF_IDF.loc[34037,'name']
max_dis_elton
#Previous Value:- 'Louis Deacon' Index:- 34038
#New Value:-  Index:- 34037

'Louis Deacon'

In [22]:
#Get the index of the minimum element in a numpy array
dis_elton_tf_idf.argmin(axis=0)

39025

In [23]:
min_dis_elton = TF_IDF.loc[39025,'name']
min_dis_elton

'Mike Hancock (British politician)'

In [ ]:
import spacy
nlp = spacy('en')
def check_similarity(vec_1, vec_2):
    

In [20]:
res = ''
for name in TF_IDF.index:
    diff = ((TF_IDF.loc[name,:]) - np.array(tf_idf_Elton)).pow(2).pow(0.5)
    if(diff == 1.4974619858032765):
        res = name
res        

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
#KNN Distance using TF-IDF
def euclidian_distance(,docs):
    
